[
    {
        "domain": ".google.com",
        "expirationDate": 1725273450.221821,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SNID",
        "path": "/verify",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AMpFgpvC3Vf5GjFac0uuzt40auzFpbsHn-CgW6Rh5CsoYSb7neCtsOY1RNEGnhVjJRigBO9BBZEblf-or6L6oNia379x6bxUyKk"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1751698800.260679,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AID",
        "path": "/ads",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXK3oF_bnQrNBEQePwVFRnl2r_clrI2S8GSQR-Q"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.706145,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AERSRtI7iVx0jZnip"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.706325,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AmOB1wDmjL5nl9KJy"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.706248,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0YjPwaMIOVPClvmJ/AGW8bdTzp-uX-yF7J"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.706406,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.706512,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.70666,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059943.962102,
        "hostOnly": true,
        "httpOnly": true,
        "name": "ACCOUNT_CHOOSER",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFx_qI7oKxH0PbTTKfWggb8VHO8lL3Qkwi29v95Zm8pCajlTItx5MVJQ8ED1vQIaHjYDqoN4czE_n1ud5zwLMPVn5ocD4vRsLzSplCJbHyyR1Tu2sQd9K7a8oD26CFJweSswMz62kiez"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059944.063861,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GAPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1:2mDb7yYPhH31fUTaCqG8tnPrbDNAp50lRSazwBETscC9ixm_PlU88LZ_ABPHmCrhqQxMYmm39syH5jJ9buH7TwQwiyoIjQ:qPIpfZm8ODBnVTOq"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059944.063957,
        "hostOnly": true,
        "httpOnly": true,
        "name": "LSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQhYhZJCX-H_Ycsx1tlbKjEBqrFUqIwvl061oPLmlWPy7QNQGDXOF8lYzjpr1-DyR95X5A."
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059944.064016,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-1PLSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQhYhZJCX-H_Ycsx1tlbKjEBqrFUqIwvl061oPLmlWPy7QNQvZbzKAmBEkTboXsCFZBG9w."
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059944.064099,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-3PLSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQhYhZJCX-H_Ycsx1tlbKjEBqrFUqIwvl061oPLmlWPy7QNQ8DwGyZud3I9Ke7T2xsEbEA."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118728,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcKoVtqZPd3TWfuyKK16NKEA."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1736523944.118775,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjIBPVxjSr5OJG9WetvCn-L7bbEYsMwua7zQjXaT1rJOi8EXd00kXDeWVspXVMVZoW4z3hAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1736523944.118824,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjIBPVxjSr5OJG9WetvCn-L7bbEYsMwua7zQjXaT1rJOi8EXd00kXDeWVspXVMVZoW4z3hAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118854,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcS0RsH0oFlE-YNjTKp1LgsA."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118881,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorc7ohMG6DgWgxRgaiHr07jVw."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.11891,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AZMUyGbUwYcuod6Ds"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118936,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFMekpXWCEGqB_8zQ"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118959,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0YjPwaMIOVPClvmJ/AGW8bdTzp-uX-yF7J"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118983,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.119017,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.119042,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.259842,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcKoVtqZPd3TWfuyKK16NKEA."
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.259911,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcS0RsH0oFlE-YNjTKp1LgsA."
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.259963,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorc7ohMG6DgWgxRgaiHr07jVw."
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260036,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AZMUyGbUwYcuod6Ds"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.26008,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFMekpXWCEGqB_8zQ"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260114,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0YjPwaMIOVPClvmJ/AGW8bdTzp-uX-yF7J"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260137,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260162,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260204,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1720799144.260234,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "511=YJSFmYnerRyJbfyts6OEkw0GV4qsiAKquu9ggpsO1Ef8Zsa62qtTINhGdLYnQhQlBUbIRAba3y6JA6ThSD5jiskADH_WoWFsawpjv-UU_O9SOagM4CBoyIyjyyzqlD6MxTuy6KQWEDgA2Ly1j8Y0NGZ-oXaWveKbseCj0swEiX8"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720539967.321085,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQIlZoB"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1745782347.383905,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Qg2gZSwcnQ_Y-ULi9_QAne0r"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1768060433,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.3.1823323768.1704988433"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1768060446,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_Q3KJSFNQDY",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1704988433.1.1.1704988446.0.0.0"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1742919730.820867,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_n",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1742919730.820946,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_l",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1725014252.377195,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_INFO1_LIVE",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "660gZBJD7iE"
    },
    {
        "domain": "ogs.google.com",
        "expirationDate": 1712054269,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7452638_28_28__28_"
    },
    {
        "domain": ".fbsbx.com",
        "expirationDate": 1744042281.490291,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_n",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1744611672.117223,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "VFHtZf0GDSrRUpJ5080P-FM-"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.706964,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a000hwhYhXr2VDt9JYFK7d0Kw6mW0cg0AbuzH9Z2s5WrPmIHqlyFeBVDixi_Jot32Qh6h6tb1QACgYKAfsSAQASFQHGX2MiDky2burEGiBj2TjKXogl1BoVAUF8yKrWdnTywd5dNg-P8l2kqjj30076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.707027,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000hwhYhXr2VDt9JYFK7d0Kw6mW0cg0AbuzH9Z2s5WrPmIHqlyF3un9tVEL9GnbHbvcc-h5DgACgYKAU8SAQASFQHGX2MizULfkE5umYn8JuItgagMvBoVAUF8yKrU4L6kU1sHtu_1Em-WPJtr0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1774294280.707094,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000hwhYhXr2VDt9JYFK7d0Kw6mW0cg0AbuzH9Z2s5WrPmIHqlyFG-pn6UTkCW1CLJZgz8c-mgACgYKAakSAQASFQHGX2MiXtYYHjQLJ3Q8nBsKhWiW9BoVAUF8yKqUI2eMe96dfkBvxD8ZN4cw0076"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1712019996,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1536x754"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1712019996,
        "hostOnly": false,
        "httpOnly": false,
        "name": "dpr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1.25"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1742951192.849987,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "100042782445854"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1727067870.663511,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "512=ZEZCrdvQp1t9InLYRhZPlK-iLLXHta8_Oda6vmSG9g-fUK0t6cgSV81VUiVOqwBrQUHPH9_a_YXu-arpjl4E5McRoQTQBIn7wwUPnb4o4kGRRItzPdD9lPXUO699WJnyTrNdweleiGgSyjzsDdht9cJymAymW4uyMrd7uL6v4A1myEqjbH5Uv3KOlwDuX_2sI8VSktvBAgDWzPOnN5qXqYkjqQv9t_gQqtEgAZ0N0PNlr_dpxFEPU0sly0VT1McTDfuiHVM-cg-EC41BJBqKmYMVU57Pfdbjc3WL8JnwsE5buHqGFRir-a2J"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1713848686.571633,
        "hostOnly": false,
        "httpOnly": false,
        "name": "1P_JAR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "2024-03-24-05"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720539965.410475,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Ae3NU9MCK1jjBKitAhjo2y9bXyakm2DCQft17xlRWIl856Wh1cOcJCzC444"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1726808687.227311,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_PRIVACY_METADATA",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "CgJWThIEGgAgOw%3D%3D"
    },
    {
        "domain": ".phimmoiyyyy.com",
        "expirationDate": 1774328692,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.1091946751.1711256689"
    },
    {
        "domain": ".aj1559.online",
        "expirationDate": 1745816689.405077,
        "hostOnly": false,
        "httpOnly": false,
        "name": "UUID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "234aa3eb-e59e-5cca-8aea-2eef38d6d838"
    },
    {
        "domain": ".kingpower123iii.online",
        "expirationDate": 1742792696.836884,
        "hostOnly": false,
        "httpOnly": true,
        "name": "cf_clearance",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "j9a2jepkv8hUYEe3Eh8.ow_DQkPj66b9PtQzuyFgygA-1711256698-1.0.1.1-yKzcpTvK6SOvOC6v5rkRRaiUggt4SQDJkvboH0Q83HqR3ueFR9D6JYV7_xeuHKEYSzvYoi03xDaiQ_8v7cnOwA"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1719032698,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.1273404611.1711256698"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1713848711,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_med",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "affiliates"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2341976701.029582,
        "hostOnly": false,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "12249d6f-e99c-11ee-a0f1-766849da7133"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2341976725.498204,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1p//77so7fcN8Ecx5gCuKtZqXjYULA5BP/kTMl61yN3l4C/SSmyMUE2uDlHfZ9wy6VCRtOL60qmKv480j+oa1dZDuphpfl0sZ3olYeiT76KOmo08WbLjiBnYr5K9VE7Yud2f/fUSu3L6uYVgH8qeBjeM856zUvR8MvSHYoQoiYI="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2341976725.498267,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y1ZRY21wZWdmbWlmemNIUQ=="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2341976725.498011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1p//77so7fcN8Ecx5gCuKtZqXjYULA5BP/kTMl61yN3l4C/SSmyMUE2uDlHfZ9wy6VCRtOL60qmKv480j+oa1dZDuphpfl0sZ3olYeiT76KOmo08WbLjiBnYr5K9VE7Yud2f/fUSu3L6uYVgH8qeBjeM856zUvR8MvSHYoQoiYI="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2341976725.498089,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y1ZRY21wZWdmbWlmemNIUQ=="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2341976701.029962,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_F",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "PbXv12ZfnmQ5mtf0nX83mSdr6ndLp1ou"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1719032724,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fb.1.1711256701354.1431948846"
    },
    {
        "domain": ".doubleclick.net",
        "expirationDate": 1774328712.699474,
        "hostOnly": false,
        "httpOnly": true,
        "name": "IDE",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AHWqTUklzLQdI23tdXJaaVSviPC9VFNAjsVQEHCVJsNYj-09VkeyOKAFLNpZa6x2"
    },
    {
        "domain": ".phimmoiyyyy.com",
        "expirationDate": 1774335758,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_PDKM9TY6BR",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1711263758.2.0.1711263758.0.0.0"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1742951185.254263,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzX2M2TesNMPueOYS1sX8iZq-dfsyYyjfNRVe-JbH9l2CGkWt0KjdLs31dg1wbb_A8J9sQ"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1742951185.254358,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzUmrJ9awEVxGl35NZCT-O0pgf177IABDw3ISs-PFpD7x_IyS1hVfcJNOocRCVFE1Ov3"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1742951185.25443,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzX4jv4rIWVW9z6dEOJXX_uRLbYg84fT6yvPeRxQh9ANGcgTp7RlmD9HGOtF2aOGNMkQZQ"
    },
    {
        "domain": ".metafi.codefi.network",
        "expirationDate": 1711416990.839103,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__cf_bm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "6bqKIp1ENVBMojHCAF9A0le56nmTVxsn2x3SpZzuutQ-1711415191-1.0.1.1-nSK.XelUBaVEnpifdJwQSZreGQ4sOq9E4pE3Msgv1BRWjzcm1zYPjyRk0ADeKjQ8mojkePg66So1DgIM8CfEIA"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1742951192.850051,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "44%3ARI6VEWH317mHkw%3A2%3A1711222346%3A-1%3A6156%3A%3AAcUSLbB7_SAOpBFbglDQyu39orMW06bsPc0cXUeHWQ"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1719191192.850113,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1C2OvmmU0nDxSj1ew.AWUuCry4vvm8M92iQxZQ1K76oKg.BmAh-Z..AAA.0.0.BmAh-Z.AWVLY1Z3AtM"
    },
    {
        "domain": ".facebook.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "presence",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1711415197849%2C%22v%22%3A1%7D"
    }
]