[
    {
        "domain": "www.googleadservices.com",
        "expirationDate": 1718552335.917181,
        "hostOnly": true,
        "httpOnly": false,
        "name": "Conversion",
        "path": "/pagead/conversion/653204524/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "EgwIABUAAAAAHQAAAAAYASCw-ZX8tNiSvMUBSAFqW0Nqd0tDQWp3ek4tdkJoQWtFaXdBWWlPN29EVHladU12UWNOTUZmdnZrd2IxM2FiZUh5TTF3VU1CVHloQlk3U2x4RUJwU2hYSWhUUW4zUm9DM1BrUUF2RF9Cd0VwyYaXvpL-hAOQAeKtg4adD5gBAA"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1744305266.557185,
        "hostOnly": false,
        "httpOnly": true,
        "name": "dbln",
        "path": "/login/device-based/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "%7B%22100019313437601%22%3A%22PNa6OeHF%22%7D"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1711985980.837391,
        "hostOnly": false,
        "httpOnly": true,
        "name": "TAID",
        "path": "/ads/measurement",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXIr3T8QlesEn2mPq3r9hKy3LNdnX27u0ligjnpGncWjcBwCHHxfuoIKDXaJ-vJ9Pn1ZEQhZyr6K5eA4oVNLzmEVVwoGZ6nqvcbgtsMVX3mVVd1-DjtnCvTFlBfuT4K_6Yvm"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1725559779.405733,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SNID",
        "path": "/verify",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AOYECSpYNfwYI9RHBzozAq_oeMtpMGLWVDeFy9t9zthyy0hYpV41VYw46SxV4FGBBlhC6a_o0hPJ3hZrc88p4x8O9CkWqGsV9Cw"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1738656000.837499,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AID",
        "path": "/ads",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXL_Mm4yNp8hDEVuoWTmn2u2WtapotcmTJj9M1SlnUUyfYpa4iKtnss"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720452737.096689,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQIlJoB"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1745974559.543693,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ermeZX-DrQOkvmetdL2c5c7K"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1720454238.911989,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_INFO1_LIVE",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "5WQZkDM3vy4"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1767974241,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.3.583799675.1704902241"
    },
    {
        "domain": ".chromewebstore.google.com",
        "expirationDate": 1767974262,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.864033894.1704902263"
    },
    {
        "domain": ".chromewebstore.google.com",
        "expirationDate": 1767977788,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_KHZNC1Q6K0",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1704905788.2.0.1704905788.0.0.0"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1767977788,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_Q3KJSFNQDY",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1704905788.2.0.1704905788.0.0.0"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768060597.240929,
        "hostOnly": true,
        "httpOnly": true,
        "name": "ACCOUNT_CHOOSER",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFx_qI6TVTlLdNA-I7MyxRlfj-ouAppwsxXigu80QgaB3Dv8K3QfE5T-QdBEiZ7vkKgVNuhUkPn1NcZqgyxQ8agc6iLvv3CXxT8a1Ut1_NUpQKCwOoDufs2s4Pr3EFDAbk5BzjLeE731"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.600712,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AXPjawa0KidjceIDm"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.60079,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Aed1f263P3W-TNFBQ"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.600845,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2zmig3kv6lm765X0/ArqXDhMMsMvTc2phv"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.600891,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "w47YWVDYvSlNjLxk/Ah1mKFALZuQAlsbVj"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.60094,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "w47YWVDYvSlNjLxk/Ah1mKFALZuQAlsbVj"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.600996,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "w47YWVDYvSlNjLxk/Ah1mKFALZuQAlsbVj"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1769782448.542867,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000fwi79-964Tqr3nOmp7sOu7apQXjNylUW3RWvOwwFoUrVISHlLz858lZBJebzxAnLQ2-6CQACgYKAWgSAQASFQHGX2MickJ2r-HaDYUu1TDiMRF-OxoVAUF8yKoRzPnAaUMrKH-6AJoRE7O90076"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1769782448.543013,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "w47YWVDYvSlNjLxk/Ah1mKFALZuQAlsbVj"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1769782449.704588,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000fwi79-964Tqr3nOmp7sOu7apQXjNylUW3RWvOwwFoUrVISHlLz858lZBJebzxAnLQ2-6CQACgYKAWgSAQASFQHGX2MickJ2r-HaDYUu1TDiMRF-OxoVAUF8yKoRzPnAaUMrKH-6AJoRE7O90076"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1769782449.705337,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "w47YWVDYvSlNjLxk/Ah1mKFALZuQAlsbVj"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1720799798.705539,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "511=cQHyphY2Dmyp1sc6FOSKky8BESHDz4aft1SMxck2T7TXZ4dJ5m3aJ-1Uwnysh9Am2zMz2gVkKPnobJ1nU-3MN5uOAydLgdrGpti59FsclzWDtAx1L7gs9CS4dp-HMkdf86rGv4RBchrlIHHNDhRMdASBizpFZ516SgbFDazDmu9IK0zmXrjNKVdumb-TBv_1gg_ejgPFCywnPDAD"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1742915478.390384,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_l",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1742915478.390496,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_n",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1726328379.515938,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_PRIVACY_METADATA",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "CgJWThIEGgAgJw%3D%3D"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1771428298.711022,
        "hostOnly": false,
        "httpOnly": true,
        "name": "LOGIN_INFO",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFmmF2swRgIhAKwhcBKO1FTSWPLD_wfae7G7cqWqMYu0qh1ODxy7uIsrAiEA4-t-kC3FyUQ6M_70Q2xBEjgx0Z0qA6bnEXRT8_boczM:QUQ3MjNmektUSnM5Umd5YTdRclFDUGRJYTdfLVNWaTg4MWhaNFV2ZWtIVzBVSG1SMW8zeGoyOEQ1T1Jfd18tbllqVkNVTFU0MWFmSXNWRkgzNmF6bkg0eEVoSHF5ZWUzWTA2amNpNk1SbWlCZGRIcGVjREV1OVJwM0NyV1RaQnhZN3AwTzh6VzJpcEZSUWg1MmlJMFBfLW9wampHdF9NMDlB"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1771428369,
        "hostOnly": false,
        "httpOnly": false,
        "name": "PREF",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "f4=4000000&tz=Asia.Bangkok&f5=30000"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1739894113.854382,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjIBYfD7Z6T8-aB8WCr_iI9hxES8Sc934br3efsEJswd9SJ3q5TBQ_AgbTWoswbkkYPDwxAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1739894113.854594,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjIBYfD7Z6T8-aB8WCr_iI9hxES8Sc934br3efsEJswd9SJ3q5TBQ_AgbTWoswbkkYPDwxAA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.601323,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a000hAi792kq7PHOVZdKN6qO2vSCyT0UJMj-G2L_hjHt6EyKH-n1XJnCgHsyebRz7-I4H7QniwACgYKAdcSAQASFQHGX2MinrZe08Y-hvGMSQDm5saVdxoVAUF8yKoifuRDOc5mhiAVBTZ-trSc0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.601366,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000hAi792kq7PHOVZdKN6qO2vSCyT0UJMj-G2L_hjHt6EyKH-n1nfObOZD0wMF0vmdJahkq4gACgYKAWASAQASFQHGX2MioUu-qmgtlAUM7yb408hPzBoVAUF8yKpYviIZRsUpqyjk8f6AxviA0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1772820525.601466,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000hAi792kq7PHOVZdKN6qO2vSCyT0UJMj-G2L_hjHt6EyKH-n1jIyoGCSX_sXKN7mii9q_NwACgYKAacSAQASFQHGX2MiKgeSO0fb1ijUCp4wmJCKmhoVAUF8yKqXx6P_e-wytbopYiXtV7CW0076"
    },
    {
        "domain": "ogs.google.com",
        "expirationDate": 1712340527,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7457409_28_28__28_"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1717524532,
        "hostOnly": false,
        "httpOnly": false,
        "name": "simplilearn_first_page",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "https://www.simplilearn.com/tutorials/git-tutorial/git-installation-on-windows"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1717524532,
        "hostOnly": false,
        "httpOnly": false,
        "name": "simplilearn_landing_time",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2024-03-06T18:08:52.986Z"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1740852532,
        "hostOnly": false,
        "httpOnly": false,
        "name": "newuser_identify",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1717524532,
        "hostOnly": false,
        "httpOnly": false,
        "name": "sl_utmz",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=|utmcct=https://www.google.com/|utmgclid=|create_type=manual_ref"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1772820533,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.82929461.1709748533"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1725300533,
        "hostOnly": false,
        "httpOnly": false,
        "name": "user_source_cookie",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "google,organic"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1725300533,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmz",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.82929461.1709748533.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)|sltime=1709748533"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1717524533,
        "hostOnly": false,
        "httpOnly": false,
        "name": "simplilearn_custom",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.82929461.1709748533.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not provided)|sltime=1709748533"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1717524534,
        "hostOnly": false,
        "httpOnly": false,
        "name": "sl_su_utmz",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.82929461.1709748533.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not provided)|sltime=1709748533"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1717524540,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.520155759.1709748540"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1743444540,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetvid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "9b825220dbe411eea07fbfd1bdb08c2a"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1743444540.41,
        "hostOnly": false,
        "httpOnly": false,
        "name": "MUID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0407FA9040C56A1B3866EEAA411C6BFE"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1717524540,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fb.1.1709748540551.78559130"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1717524541.85581,
        "hostOnly": false,
        "httpOnly": false,
        "name": "li_sugr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "f0228993-3f3d-4f23-a500-b474ba6e7e3e"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1741284542.85588,
        "hostOnly": false,
        "httpOnly": false,
        "name": "bcookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "\"v=2&713b9a1e-6d34-4544-8949-dfeeca1c39df\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1712340540.983183,
        "hostOnly": false,
        "httpOnly": false,
        "name": "UserMatchHistory",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AQIBqGKULTMRGAAAAY4U9FeTP6nHfsaAjJy5lDQnRwNv5I_vMMKhYAnZEoMah4xC014StoU5fHff2A"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1712340540.983248,
        "hostOnly": false,
        "httpOnly": false,
        "name": "AnalyticsSyncHistory",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AQIMj-M0dXj35gAAAY4U9FeTA936buTGVMAqFo75U2uYBLPVeylDk-5QsaM7MwlfMQEeHf1i-HMGJxT-ZPJYiA"
    },
    {
        "domain": "www.simplilearn.com",
        "expirationDate": 1772906941,
        "hostOnly": true,
        "httpOnly": false,
        "name": "_gd_visitor",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "655da610-4301-4dfb-8c9c-f4658fd7e52e"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1741284542.263819,
        "hostOnly": false,
        "httpOnly": true,
        "name": "bscookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "\"v=1&20240306180901485f9865-848b-409a-88f6-b384951ad94aAQFdd3ANWX2qvVgAr-4xPYskJqYuUrdG\""
    },
    {
        "domain": ".disqus.com",
        "expirationDate": 1741284541,
        "hostOnly": false,
        "httpOnly": false,
        "name": "disqus_unique",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "91iol497jv9uv"
    },
    {
        "domain": ".6sc.co",
        "expirationDate": 1772820577.65602,
        "hostOnly": false,
        "httpOnly": false,
        "name": "6suuid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "15ef2117dfba1b003eb1e865fb000000cddf5a00"
    },
    {
        "domain": "www.simplilearn.com",
        "expirationDate": 1741284542,
        "hostOnly": true,
        "httpOnly": false,
        "name": "slirequested",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "true"
    },
    {
        "domain": "www.simplilearn.com",
        "expirationDate": 1741284542,
        "hostOnly": true,
        "httpOnly": false,
        "name": "sliguid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2180cb6a-ccb4-41cb-bd30-fe6ee0fb1b8f"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 2025108542,
        "hostOnly": false,
        "httpOnly": false,
        "name": "amp_c6e1ea",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fI7HNFlXhTnY79Uq7iV1j-...1hoaf8krf.1hoaf8mpc.1.0.1"
    },
    {
        "domain": ".webengage.com",
        "expirationDate": 2025108543.728358,
        "hostOnly": false,
        "httpOnly": true,
        "name": "WebKlipperAuth",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "k3IWkhUUaW0BUm5EMOes"
    },
    {
        "domain": ".webengage.com",
        "expirationDate": 2025108543.728484,
        "hostOnly": false,
        "httpOnly": true,
        "name": "_we_rf",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "https://www.simplilearn.com/"
    },
    {
        "domain": "www.simplilearn.com",
        "expirationDate": 1725300552,
        "hostOnly": true,
        "httpOnly": false,
        "name": "g_state",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "{\"i_p\":1709755752588,\"i_l\":1}"
    },
    {
        "domain": ".simplilearn.com",
        "expirationDate": 1772820579,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_CG9EYRX7VL",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1709748533.1.0.1709748579.14.0.0"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1743444579.20052,
        "hostOnly": false,
        "httpOnly": false,
        "name": "MSPTC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "nTcn-iGX33zR4KRTcc6YgIRNp3eEa9wXPjGo1HPijlk"
    },
    {
        "domain": ".freecodecamp.org",
        "expirationDate": 1772820703,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.834611676.1709748704"
    },
    {
        "domain": ".freecodecamp.org",
        "expirationDate": 1772820704,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_RSZ1QSGJLW",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.2.1709748704.1.0.1709748704.0.0.0"
    },
    {
        "domain": ".freecodecamp.org",
        "expirationDate": 1743444704,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__gads",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ID=4f3116202c085213:T=1709748704:RT=1709748704:S=ALNI_Ma0h40BBR8ugSW1DWqEVSUmcRMjiQ"
    },
    {
        "domain": ".freecodecamp.org",
        "expirationDate": 1743444704,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__gpi",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "UID=00000d2a6cdf4760:T=1709748704:RT=1709748704:S=ALNI_MbCDFSHE0bZTwg1B37ur_LrG5Ey-w"
    },
    {
        "domain": ".freecodecamp.org",
        "expirationDate": 1725300704,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__eoi",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ID=d74bd4b6198b53d9:T=1709748704:RT=1709748704:S=AA-AfjZvl9nCGE_Rm_uDo4g58H5l"
    },
    {
        "domain": ".freecodecamp.org",
        "expirationDate": 1741284705,
        "hostOnly": false,
        "httpOnly": false,
        "name": "FCNEC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%5B%5B%22AKsRol-t4MuKiz0vSaH3npgYgW84FOmjDLI46NAyewHtJwdPGN2GLz3XDCjpksc9wUxolHCCT_nhzzcE4UFTV81QRnzTVh-6db6CUwJnjS1wLDBbwKcQgT3vP2xPXwxOP_ns-Lqs6a-CXJFzuJzr1tQKWhegCiFwdw%3D%3D%22%5D%5D"
    },
    {
        "domain": ".stackoverflow.com",
        "expirationDate": 1741284798.706146,
        "hostOnly": false,
        "httpOnly": true,
        "name": "prov",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "56b431d7-9ee4-4a8d-9265-4a4b8a1491fe"
    },
    {
        "domain": ".stackoverflow.com",
        "expirationDate": 1743444798,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__gads",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ID=e84e16ab6befbe19:T=1709748798:RT=1709748798:S=ALNI_MajNAQpTQ4B-O4AoMu9fnHMPYbZ2A"
    },
    {
        "domain": ".stackoverflow.com",
        "expirationDate": 1743444798,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__gpi",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "UID=00000d2a6df2f0ec:T=1709748798:RT=1709748798:S=ALNI_MZxo_ny2A2qcZI3dqREsMLnU0ozGA"
    },
    {
        "domain": ".stackoverflow.com",
        "expirationDate": 1725300798,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__eoi",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ID=b6db8bce18353f79:T=1709748798:RT=1709748798:S=AA-AfjZgIVNZGuWTNQXGdOyHtZie"
    },
    {
        "domain": ".stackoverflow.com",
        "expirationDate": 1741284801,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonAlertBoxClosed",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2024-03-06T18:13:21.591Z"
    },
    {
        "domain": ".stackoverflow.com",
        "expirationDate": 1741284801,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonConsent",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "isGpcEnabled=0&datestamp=Thu+Mar+07+2024+01%3A13%3A21+GMT%2B0700+(Indochina+Time)&version=202312.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1"
    },
    {
        "domain": ".freecodecamp.org",
        "expirationDate": 1772820850,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_FKVJ4HT3MH",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1709748703.1.1.1709748850.0.0.0"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720452755.455385,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Ae3NU9PLePmFMal1NkjoOqF1GhCzKkLABWDTpIDbWRTnb7f3mfflfTivzg"
    },
    {
        "domain": ".doubleclick.net",
        "expirationDate": 1772820539.982511,
        "hostOnly": false,
        "httpOnly": true,
        "name": "IDE",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AHWqTUmORHjBSZnnFlZKSl56-mpmghj3XNhve9TNqcm4KxrVkYQP732dlQ6RJMW4"
    },
    {
        "domain": ".vuahanghieu.com",
        "expirationDate": 1718552383,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.1934594331.1710776383"
    },
    {
        "domain": ".vuahanghieu.com",
        "expirationDate": 1773848383,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.1790457975.1710776384"
    },
    {
        "domain": ".vuahanghieu.com",
        "expirationDate": 1718552383,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gac_UA-131055830-1",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1710776384.CjwKCAjwzN-vBhAkEiwAYiO7oDTyZuMvQcNMFfvvkwb13abeHyM1wUMBTyhBY7SlxEBpShXIhTQn3RoC3PkQAvD_BwE"
    },
    {
        "domain": ".vuahanghieu.com",
        "expirationDate": 1742312385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "customerUniqToken",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "af52a6598f689a06c68228bf77aa5fd1"
    },
    {
        "domain": ".vuahanghieu.com",
        "expirationDate": 1718552387,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fb.1.1710776386571.1116592406"
    },
    {
        "domain": ".vuahanghieu.com",
        "expirationDate": 1718552387,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_aw",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GCL.1710776387.CjwKCAjwzN-vBhAkEiwAYiO7oDTyZuMvQcNMFfvvkwb13abeHyM1wUMBTyhBY7SlxEBpShXIhTQn3RoC3PkQAvD_BwE"
    },
    {
        "domain": ".vuahanghieu.com",
        "expirationDate": 1742312386,
        "hostOnly": false,
        "httpOnly": false,
        "name": "token_user_query",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "e3ig9avdnmsga4zhn3avq"
    },
    {
        "domain": ".vuahanghieu.com",
        "expirationDate": 1773848414,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_LXSK2XTS5Q",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1710776383.1.1.1710776414.29.0.0"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1742312441.045921,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzUlrKmAGlp3cEblUZqPz8Zdg9_MqZdYEwIeaHuBiUZt8Kf5Uu6ZJlwNPPpEyycOhbKo"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1713372489.679143,
        "hostOnly": false,
        "httpOnly": false,
        "name": "1P_JAR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "2024-03-18-16"
    },
    {
        "domain": ".openai.com",
        "expirationDate": 1741884489.063579,
        "hostOnly": false,
        "httpOnly": false,
        "name": "oai-did",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "84fcba5a-7d27-40e7-863c-45bc1bb177a6"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1726591689.185719,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "512=nhl7TBwIH17GIOkELp8jW0iV7Cj9NPby85S4Lm9IGA1rpKrkzxYh4Zyv9NP7Fr6d8PIK7zssxvUut7a45dn3PiuulU-5808p4YzZG7SC13K1MSndmLKs74trZaBj2aepRNq713q2nk8P7hhAhutyvkLV1LYOsgxUG70qrOEhqPCRM4ga6WbROrc-XpHp-LtgYTnz4xwvdlVm3uhq6KSd1S4Bs5IXIGBoBDMXbC3gQ9oc9s3wsn0YLL9zZcz4yEOUULJMeFYNvGPnlHIoI-i5WLNE5fgbw3hy29kvgVJf9uoXOXmrof6cP6uPRO4m"
    },
    {
        "domain": ".openai.com",
        "expirationDate": 1742316539,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ajs_user_id",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "84fcba5a-7d27-40e7-863c-45bc1bb177a6"
    },
    {
        "domain": ".openai.com",
        "expirationDate": 1742316539,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ajs_anonymous_id",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "74e765a4-dc8d-4f7a-bef0-3b415ec6ce08"
    },
    {
        "domain": ".auth.openai.com",
        "expirationDate": 1742316505.199268,
        "hostOnly": false,
        "httpOnly": true,
        "name": "cf_clearance",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "nXkNhwCPOXDT5Ly21WjUqfGnRA9ZpH1RWd5ulfFc488-1710780505-1.0.1.1-PDLAoAy7mw.cdxMNPeY6OdGrr0_VTPxwHqMXyrUKQRF6l2lbWkv9feEf3lpg9MHjwGqDMLcIB_DkZqh_hM_E.g"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1773852513.049774,
        "hostOnly": true,
        "httpOnly": true,
        "name": "LSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:g.a000hgi793bPfn9J-I4tyMofa3zTIEgFbqyrlJOrtPEw5zSJ9qesKly90mTkwXcSXgzq-WlonQACgYKAZISAQASFQHGX2MiIqokA5jzyyDSd4MQiAOhWRoVAUF8yKqWyDWJSi-L5EYu-aylqhq-0076"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1773852513.050072,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-1PLSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:g.a000hgi793bPfn9J-I4tyMofa3zTIEgFbqyrlJOrtPEw5zSJ9qes-qh38YLECHBjc-mM4f47xQACgYKAdkSAQASFQHGX2Mipz0K6OoOJAnbOzTyoSkPNhoVAUF8yKpS0_RSckg-jfYKIPaeKeHa0076"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1773852513.050345,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-3PLSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:g.a000hgi793bPfn9J-I4tyMofa3zTIEgFbqyrlJOrtPEw5zSJ9qes3gYpPCIu_SCfWGKP8RMrswACgYKAfoSAQASFQHGX2MiQyYS3ogopo2S302FmF4qJxoVAUF8yKqiFUFhYTEL2e19nm7VQrjL0076"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1713372518,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7474609_28_28__28_"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1773852519.819022,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GAPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1:UXLRPbUViQ9rfBuAAH7X_XExpqOrBvf7JfqVIvLTZEGOeppCrgtQgoZ4GsLhc2mIOXNKD0tZ6VRpEE8b5-CMvuDNZAEC1Q:x_yqQIjGrqtDgxOS"
    },
    {
        "domain": "auth0.openai.com",
        "expirationDate": 1742338120.658406,
        "hostOnly": true,
        "httpOnly": true,
        "name": "did",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s%3Av0%3A5b836300-e547-11ee-8cbc-03e17be3ca78%3Ad8d20dcfb78e42c7133c616123c515f175a382348f541b97739916f287dd4762.JIXCx88m29aa56fvH3hooZCcsKGZE%2BW6KStBa8%2B80hQ"
    },
    {
        "domain": "auth0.openai.com",
        "expirationDate": 1742338120.658588,
        "hostOnly": true,
        "httpOnly": true,
        "name": "did_compat",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s%3Av0%3A5b836300-e547-11ee-8cbc-03e17be3ca78%3Ad8d20dcfb78e42c7133c616123c515f175a382348f541b97739916f287dd4762.JIXCx88m29aa56fvH3hooZCcsKGZE%2BW6KStBa8%2B80hQ"
    },
    {
        "domain": ".openai.com",
        "expirationDate": 1742316525.641157,
        "hostOnly": false,
        "httpOnly": true,
        "name": "cf_clearance",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "61Q2HqZg3N5vHlC5pXAVBi._bsHNUUwDT81r4kMLuwI-1710780525-1.0.1.1-3YPLBVAepKw7Zjb.Ox4HLDt2qurmT.AqF5GHq9FgijeTvqdGftZuUW9fXhouZlVIuRiv.4dIh03gxUcyl8ikFw"
    },
    {
        "domain": ".auth0.openai.com",
        "expirationDate": 1742316525.897104,
        "hostOnly": false,
        "httpOnly": true,
        "name": "cf_clearance",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "MWn90kErX6mq8PDdk90J4Z1TL9e6Tgj3_LpjjZYX7ng-1710780525-1.0.1.1-hX2fyUePG8UpP3.2oGOXnxyU4YVgrwD38nwqr9rePwGESOmQ9Q0jGhcnFP5TNdxCIn0MyAawHvwzQjQv1gM5tA"
    },
    {
        "domain": "auth0.openai.com",
        "expirationDate": 1711990142.656516,
        "hostOnly": true,
        "httpOnly": true,
        "name": "auth0",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s%3AFgpH3uP3qIhtG3r99azlhViFqQGsSdMY.xxli0KCXuGN9Eo4O0miVpKV6WhzPhAcsYYRP9NN%2ByWQ"
    },
    {
        "domain": "auth0.openai.com",
        "expirationDate": 1711990142.656673,
        "hostOnly": true,
        "httpOnly": true,
        "name": "auth0_compat",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s%3AFgpH3uP3qIhtG3r99azlhViFqQGsSdMY.xxli0KCXuGN9Eo4O0miVpKV6WhzPhAcsYYRP9NN%2ByWQ"
    },
    {
        "domain": ".openai.com",
        "expirationDate": 1734196922,
        "hostOnly": false,
        "httpOnly": false,
        "name": "intercom-device-id-dgkjq2bp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "a851cd0b-5682-43dc-9af4-f4da13fb4517"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1742319604.228295,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjIB7F1E_P8Ly5lTWCs53WWZyoxfu8B0yC0guFlYJCL5VGiB97aqqzlPkD4kzTTv-QRiZxAA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1742319604.228583,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjIB7F1E_P8Ly5lTWCs53WWZyoxfu8B0yC0guFlYJCL5VGiB97aqqzlPkD4kzTTv-QRiZxAA"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1712161320,
        "hostOnly": false,
        "httpOnly": false,
        "name": "dpr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1.375"
    },
    {
        "domain": ".chat.openai.com",
        "expirationDate": 1742402887.758616,
        "hostOnly": false,
        "httpOnly": true,
        "name": "cf_clearance",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "u6tqeOlfwj3831RlcyLiqJnzQG0aAMvlA_GPfcXInoU-1710866881-1.0.1.1-C.AzY7cIdfgwxUyHXwh07tbdv7grM.d_XUA8nLbU2YveDc71n4PZY2Twd1zBVOLOioLSNgL0iM6AKv98f9hkbQ"
    },
    {
        "domain": "chat.openai.com",
        "expirationDate": 1718642889.360562,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Secure-next-auth.session-token",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..rZYCJCuKfVU7ShxC.TJglpiCRGHjnSLjt8dKtjU4SyQ6YCoVCUd-GSFRc7Flf3wipAwFBeP_yQwYjxsP_JcFbMKDMy7LYA9_TsxdpuDS4hFaZ2SCC9mnKh0sPt8RUcVd-FYwtLY-cM98r5Zw3NQHbnjxGgxNNBLxcD6DMwk7UPIL41or3WJRxhshhA1PScXiWRi6_G51g9-DwlrXFJpySy18H5HyDd6xlK5-OedRPOZ8zeYTpBKio98L3jyFRQoxH_5rcJnSfSnhiI9_aqctP8XNq9qYSgfz-7mJvMN2k6uBfjRtxCHVfFIenUQAwtipqraqqtDdwKk-NLbzF_fssnkZObU0EMRQsioD3VpMAsmtPqR7vW3G2dPEjFJ8cj6UQnbh_P89VSGfpWzE_EuDNckBab9B0MazPHo21TniEHXML81CDIiryB6plzMrV93Y-QZTi1XTezxTNTi1ey2zkU8Q2R0REPuJzVuHN5cC_RW6VpshGlLQgg1qczoZ2FqHqnyOhpNkDkmWR3nVqB9M1ina3qJCeeuGfVyctC3FK0p9Fs0kHy7ZLzCJN-nVTqXfLTSZfkDjUbHsfkSCzfxUrriKM31wmoh3yewael59C_soxG3PmbjN77fRjqyLiVks7xXwD9ozcPvKJAm2flMrFY_YcHa1HwJ09OgGcDhK-R3ZibB-BTpTJEHciT26wG-wLMIV2NZxI8hvjBrOit1uzqgT6n87hZmlH5wfu0gCiiC7fGP5QMloiD8ptCPD_o41JIZ7ohF6SgPcC6IV4vyoVpUQhfmzNC0MrYSjXR9Fx--BAdX9gEDJzR7SDToiCG2uCB7IHN1vZ6hcXanPsJNyKfxG2bMX5m5uNIeIG8a2qiFO3_hj0W_6GMd43e_9e77MRrYrq9-vCGrdBR14zJ1TxgUdnmkZ3Akq3CiVDoWsvk6eNgpYVeUzJsnKxkaKLz_YPAHU0a-gXELXcZ94qyzOe2m_3soXWzdWE77GZEpf9ZsehMgzx-SKpH7Oq-H1TmILCeafOXsEgdt6ji9qF03eLLXYUmH3a4txgMHIQEzRTWUylqC9bUFjSGoEmjy1UyUT8M5mlhmjBbNds26NW2d3w_7idPg6T9HMbauUdB490tl0MuQp35RKAT5xZFJaupcaF6K_U4tLPMd66KwgNQcmdnXd9c08MoApY0yoZNj5NinfiknAOS_05oSoNzo9ruFpIuTi8O0avj-Mf41-TuMz9fs1vvCOB0KKOoOcxMnuvcF4bfpQBTZTkeAj6cTUCDTL7M_UDy_7HoPgIfOJOEFA05-Bfik9IY1GVmqjwdqlPLqF51uQrC7N1lg1GB45bBszLKU405VeJyZpoHw2pNSN5mYidqy3vJ-YcSUOcRFZLeCmzNIhUci0_OemV7DQYuE14MlKBj8rYCjcCwYRY0ZN6oZ2LHGS_yrgGHQ4eIL3Xf4JWDDu-4vzKAC1xLMVMYl6PihzfuEfNQvh4IVJmJOXynYNLmrmREYcRQR91L-aoHnHDMqcLBVXiwm5MAvsBEkQb-kBTPzdd-uE2n2J_XO3kCehN6djC5ofHE-A7KZHI9B5PWCC0VTvoo7q5tYGppKGt49xlucnCKyVstpThg12ViHSMM1KLZRSzioidRIpnsK9s0cTqfXK-fJEUjJpJTY5hhrRjh7e6cnK2S_X26LfxZrgvP_jHpfAAD4oBmWM4I00ZVcgpx_Fz0J_hnhJfIHPdcUaRA3Kgrsi7KV375CBfIveUGkFuNlbJJRSXfUT2jlNOM9KFWe2n5nHWaEXXiWquXITQWa7wkGyOJxet8ziejx8pbFRvPHNzqCtBURuMf2jUXCShVF_2iJT0_52VgGRvGZeupbNl1QOy9HEScNv-0Ib0QOjVY8Sk8OSF-VaJF0nYR23xVmnZLIepevVqA2u6yGd5XddFmWTjvCa6vxgl1Xm0PRXJMkQZXzmCI5b3s3llX-SHSfkVm-sEJpVdLTs-hOp_IvHjG-AxBDO_uk6wV0Mrqxh5LZ_vTUcqe_WAc49tJqfCTuN-IeaOTAtFyK6MyUflL7E0BBQHcHMrFAQKcGO6VhEy0bZVAK9wvKQwu_PRU6RFuNagL4PEa60gkgcXcJd58dH27SD1HgAPSOhhxqmap_H-YPR2wY2G0QEOgqtFEVbP7CJoaPZ1claMTTii2xS2jMDsLJJPv83nXyAcgJlRrZ6zMAEc0FFy9B-R8gZC2q-0PX2EPAnHDzt7ogMzxLDoWh_o2d9tI0g90bQ6VSVWB3KmZFpFvsJsCv8xJSxr9qUtXtTHvmTIUcOJh5o82gXwOVckh64tyEspdxZBX6C1NcwiWENmLyQtZCVeRSd-0wuQctkTSupEDcdkf0-yGUnPHLyF3ghAw6xDj6pXmjQAHr0xIriGDPdQdx-5RBdEM7zLPAXqPJfgz-61fbnBV6BrE7GXagFx1U79nX3szxPqPwcbFc2NTZ55b7v621s2Ct9y1zNwi7NBDMFagitPD07-1rMrS8Tg2sCw9e1kiMQlKtwYSxsVDcqOZyJdkCTflE8r-mGc2wB3vfjdPsuWh8cUuJhCB641ct4njlRx01HMjmO_dK-seSHxeXWLVBKQP3_Wmxn212YQIsC3sMa3RqIB_Cp07KR0DT9N0OP_cvgYMtdHYG8mS_EwZIG8U7GexBc8jAkwVDipzrMDau8Zk_DrUip72jl_3BT6ViK-_5e6vH0_9EhX2gPjiDbqkKxnz3Hdf7e-C-ptV5ulh9ot72PwNUHlaBpW6mwxU0ZsKBQBdePsyhUEnZFKp_yhzF4.RJfPdNb7nQ-o4exFCdvzpg"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1712161320,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1396x686"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1743092524.688574,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "100019313437601"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1745974568.182761,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "IB0CZkPeJai6tmf30mC3nDzR"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1743092513.221322,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzXKHCH-YJA6LZ1Oguacbnnc3yMhp9UlK_u89DSmtJ8oEwOQZBrJOgmdM_Crzbfb87SF3A"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1743092513.221376,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzWDba54Ey_5uXQXf72kL6tjK6mdef-lKOTAvbgqoO5WNWBbF5I3MSjS2L8S72HxSmck"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1743092513.269681,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzV7Ke0ea3JwC3bHllNctIYAtseiSiQ260rHOgztuWt3oYrf2n3P1o2VrQzjrGRyGKNHJqw"
    },
    {
        "domain": ".facebook.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "presence",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1711556524050%2C%22v%22%3A1%7D"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1743092524.688664,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "13%3A5HWzrHjlzz4p-Q%3A2%3A1711414558%3A-1%3A6270%3A%3AAcUDxxW0lwVV9wMX6IMgb65ufgYdEx-S4ZTATS1F-g"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1719332524.688731,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "16tLbQpb64EfWrZap.AWW6WjAOMBKISnUM7s0jzwO7Gw4.BmBEeq..AAA.0.0.BmBEeq.AWU7wTbi04g"
    }
]