import { ScrollToGetPost } from "../core-playwright/AccessTradde/scrollFB"
import { seedingFb } from "../core-playwright/AccessTradde/seedingFb"

const cookie1 = [
    {
        "domain": ".google.com",
        "expirationDate": 1706197015.826537,
        "hostOnly": false,
        "httpOnly": true,
        "name": "TAID",
        "path": "/ads/measurement",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXKuY0nPT0P7f6LG04eCPlkPnsQpibfZ0TcHyeWhIGB8OqiuuiHbi5Km16PeEGkO3In_ZEsQ5XzKiHYh2TbPzocTd16_rLBnWC9Zm3hZ1lIRUpU1IFvGyihhflf6tBwUGFcj4A"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1705851070.024838,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/mail/u/0",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gmail_ps=CrEBAAlriVfbjvYCO6pE7yB0sa7cEjsS1rG56wHLqh7Gz6z-3C_MxX67z6L7MTXExQa8xmQeQa4mH-xRIMuAea7e-iCkr-icK6Yw0sAuXzZ8J-bk1maHLScX4yGxQZlg06eUkJnjXbctcilEA_fMp5LYAnQOIhKeCLWuySUIcFBmDT6tChsEk9UkIV4OoWN8ZMN7QZReN7Jt6-yA90Pe3PS8rUgRt-M-0f5J8_LJqOZ4Juf-EMOvgK0GGuoBAAlriVdNkz7MruYAXhEmbwyMpz_AvCF8P9s0u6BTB_juJqhQq0c8SR8afg7mOo1NTLhjASZifYzs9-HxSluI9bLSdc0HckXEwBnLb6OzuGOmgEIKHY5itY3ROCeMPzFizfSP8gNU9gK3kdtzkW-MclBlBWdgHS180W64_B1KQrpFGQxyykcVelUwYpwaaGQgvppfvhwcsFBM5eguBzxDiqo0xyWQEDtvkBxYnzo_Me-kKN4G2yuTbUoXHNtFcTA7qtjHzl3aEVzjSsqyarl2YeFb3MJXh_dvn9V8wqF8BQt9SOTq31P0D2tBMAE:gmail=CsUBAAlriVeqmzEcCPFAhOtXKDrF5wMRDy6KjDW9b3IL_GDlVOYoMgWZS_aH3-Nq6-warg626fYLeXzAxBJyge-uhgp_prqi9E8dNUOGaDuNrzHXydjxWU--0FwvAEqOBgIBk26_PLmzx6dP_Yx6AYsgum3F9YyTsiG3O4bq8p15ADfA6KfZmRouJaPpJ1hgi3oZHpT559e40zqG1eKlJIkvFvoXk3hDxCSEzcDx2-NANE_nyUZnZheVVj_uH-qN5Gxzut8LhYwQq6-ArQYa_gEACWuJV0E4jA_CigVADiwt6xUTVq6d7ZloyRj95Rh9wtAQgUFads3ATb0mzOmOWh6eHVZtYII2qAF8RsmdB4AE6j1AxjB2hMbhWvU0MCBLE_gE87kFizPVL8a7dufR7uRAObNvroUNNkdWWOhM-Z7RPMMN7jJQ4I6teO54hR_n4-3mMP4XUySXQOH6gbf8VZB6YDSeeURqbURqfU3s3138XpQAQyVYHu02ubLOcpsRG0XVO8c22-xqO5gFW3zdYbdjDm7copcmx7fvmfU3ct5xKPw3YbKeDmSiFV-elOcsnZSsQHUq5Js8Agwd1YzYZpg8XmqteYFGjymhC_d9BDAB"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1705851073.374952,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/sync/u/0",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "bigtop-sync=CsEBAAlriVcLnOg5LRu4ftfwo3260d_UmqxeSC32SDhcl-WT-NM9DnUC0xVDQGt1WOEuTFmt_n1LfKYsWGwMeMpAUOauIZuUwwRbGqQNWEjMW8KgdSB-TedLghYTmVA3InikDJrBp1KRLJiZLq4BopxfySgiQBgDjWrjSGydZrgRUPweooOgJbb5KMuMI4Z_3lTmYJIILvpXEzlpOPAtEZEafTa5VKqXwp71839qn2c5g42DfHiNXc_NBjojpvgd8qfbjBCvr4CtBhr6AQAJa4lXme0ztZHe8AN9lcGNoI6vAM-do3e5hwou2iQdq4qAzhJP8bl1HdlGEaHeF7F5jDPWeYcIWMj7lcxswL0QH-hEh3AiO5b1pL1rOZstVXQUmVZMpvCWolFAMHaBKwJfv1ACuPXQw_zBJMNJzYFdyHgO-YYrHHgV_n9ERmy5bgWdh094bvLPS91ydPollJhjdrH68Q0hqsJ0Jc-XjIW_tB27bRbo2lPQ6Bqfyqayj3ezoLHD4FW6DI3xhOuprK6bZLKqDvlhlHfwqYRfpSMWfOaHmvbx-BhBtqVB2Y1oCN1uMVbdFhePeayibEYYFsBRiVI8AFcpMAowAQ"
    },
    {
        "domain": "mail-ads.google.com",
        "expirationDate": 1705851074.348254,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/mail/u/0",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gmail=CsUBAAlriVeqmzEcCPFAhOtXKDrF5wMRDy6KjDW9b3IL_GDlVOYoMgWZS_aH3-Nq6-warg626fYLeXzAxBJyge-uhgp_prqi9E8dNUOGaDuNrzHXydjxWU--0FwvAEqOBgIBk26_PLmzx6dP_Yx6AYsgum3F9YyTsiG3O4bq8p15ADfA6KfZmRouJaPpJ1hgi3oZHpT559e40zqG1eKlJIkvFvoXk3hDxCSEzcDx2-NANE_nyUZnZheVVj_uH-qN5Gxzut8LhYwQ-6-ArQYa_gEACWuJV0E4jA_CigVADiwt6xUTVq6d7ZloyRj95Rh9wtAQgUFads3ATb0mzOmOWh6eHVZtYII2qAF8RsmdB4AE6j1AxjB2hMbhWvU0MCBLE_gE87kFizPVL8a7dufR7uRAObNvroUNNkdWWOhM-Z7RPMMN7jJQ4I6teO54hR_n4-3mMP4XUySXQOH6gbf8VZB6YDSeeURqbURqfU3s3138XpQAQyVYHu02ubLOcpsRG0XVO8c22-xqO5gFW3zdYbdjDm7copcmx7fvmfU3ct5xKPw3YbKeDmSiFV-elOcsnZSsQHUq5Js8Agwd1YzYZpg8XmqteYFGjymhC_d9BDAB"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720798613.894779,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SNID",
        "path": "/verify",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ACX8J6N4ohGF6MM4wcQV8Ac3YtU3ZocmbtYhh4rk_muLdedeYGgnTNbz253_q6vn1uM6XbW4K3ocruu1tO6h3jq8cd6eocpW7A"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1705851088.10318,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/mail",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gmail=CsUBAAlriVeqmzEcCPFAhOtXKDrF5wMRDy6KjDW9b3IL_GDlVOYoMgWZS_aH3-Nq6-warg626fYLeXzAxBJyge-uhgp_prqi9E8dNUOGaDuNrzHXydjxWU--0FwvAEqOBgIBk26_PLmzx6dP_Yx6AYsgum3F9YyTsiG3O4bq8p15ADfA6KfZmRouJaPpJ1hgi3oZHpT559e40zqG1eKlJIkvFvoXk3hDxCSEzcDx2-NANE_nyUZnZheVVj_uH-qN5Gxzut8LhYwQ16-ArQYa_gEACWuJV0E4jA_CigVADiwt6xUTVq6d7ZloyRj95Rh9wtAQgUFads3ATb0mzOmOWh6eHVZtYII2qAF8RsmdB4AE6j1AxjB2hMbhWvU0MCBLE_gE87kFizPVL8a7dufR7uRAObNvroUNNkdWWOhM-Z7RPMMN7jJQ4I6teO54hR_n4-3mMP4XUySXQOH6gbf8VZB6YDSeeURqbURqfU3s3138XpQAQyVYHu02ubLOcpsRG0XVO8c22-xqO5gFW3zdYbdjDm7copcmx7fvmfU3ct5xKPw3YbKeDmSiFV-elOcsnZSsQHUq5Js8Agwd1YzYZpg8XmqteYFGjymhC_d9BDAB:gmail_ps=CrEBAAlriVfbjvYCO6pE7yB0sa7cEjsS1rG56wHLqh7Gz6z-3C_MxX67z6L7MTXExQa8xmQeQa4mH-xRIMuAea7e-iCkr-icK6Yw0sAuXzZ8J-bk1maHLScX4yGxQZlg06eUkJnjXbctcilEA_fMp5LYAnQOIhKeCLWuySUIcFBmDT6tChsEk9UkIV4OoWN8ZMN7QZReN7Jt6-yA90Pe3PS8rUgRt-M-0f5J8_LJqOZ4Juf-EP-vgK0GGuoBAAlriVdNkz7MruYAXhEmbwyMpz_AvCF8P9s0u6BTB_juJqhQq0c8SR8afg7mOo1NTLhjASZifYzs9-HxSluI9bLSdc0HckXEwBnLb6OzuGOmgEIKHY5itY3ROCeMPzFizfSP8gNU9gK3kdtzkW-MclBlBWdgHS180W64_B1KQrpFGQxyykcVelUwYpwaaGQgvppfvhwcsFBM5eguBzxDiqo0xyWQEDtvkBxYnzo_Me-kKN4G2yuTbUoXHNtFcTA7qtjHzl3aEVzjSsqyarl2YeFb3MJXh_dvn9V8wqF8BQt9SOTq31P0D2tBMAE"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1751612400.826728,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AID",
        "path": "/ads",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXLOj8MtaAhqJQTsEMLp-eO4SLZhAaip--DJ_Kw"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1707579015,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7378050_28_28__28_"
    },
    {
        "domain": "myaccount.google.com",
        "expirationDate": 1707579055,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7378051_28_28__28_"
    },
    {
        "domain": "www.google.com",
        "expirationDate": 1707579057,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7378051_28_28__28_"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1707579067.178064,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GMN",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1707579067.17845,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GMS",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1707579067.179139,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GML",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720539069.779594,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQIlZoB"
    },
    {
        "domain": "contacts.google.com",
        "expirationDate": 1707579074,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7378051_28_28__28_"
    },
    {
        "domain": "ogs.google.com",
        "expirationDate": 1707579074,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7378051_28_28__28_"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1720539126.732155,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_INFO1_LIVE",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "JFdgBACka78"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1739678572.972399,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "9wmgZeTSssgc7QcoYWocPowH"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1705723375,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1536x754"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1768059417,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.3.1030820132.1704987417"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1768059891,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_Q3KJSFNQDY",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1704987416.1.1.1704987891.0.0.0"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1707710510.445461,
        "hostOnly": false,
        "httpOnly": false,
        "name": "1P_JAR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "2024-01-13-04"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720539126.368127,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Ae3NU9MwyUBHsb3FAl6mMGRWxMTvKSP4ZRROWbl_ZsEdhmxsj1lSW2aGH_8"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.556671,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fQiiPdLu0pyCtWook8rSb0OfvXSUhaHDOz_brEHZG_gyWqe-nv5sY4XAtcTLyjyzHDUzoQ."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.556807,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQiiPdLu0pyCtWook8rSb0OfvXSUhaHDOz_brEHZG_gyWqe-TLCqeJrG1z3SdUHh_00COw."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.556913,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQiiPdLu0pyCtWook8rSb0OfvXSUhaHDOz_brEHZG_gyWqe-HBLjuqPc4TgD3cbIqD34PA."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.557277,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AcPi0JriLk5d4bqWw"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.557347,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Az0qt5kJkOouW5AWr"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.557398,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "isqmXl8QGHzTtwj6/ASNVxUWfy6b9ML_H8"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.55747,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "MtqtvSoZowUKlMU8/AeZ9f2wc9nvl6Zwot"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.557532,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "MtqtvSoZowUKlMU8/AeZ9f2wc9nvl6Zwot"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768190509.557592,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "MtqtvSoZowUKlMU8/AeZ9f2wc9nvl6Zwot"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768190509.557656,
        "hostOnly": true,
        "httpOnly": true,
        "name": "ACCOUNT_CHOOSER",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFx_qI7p1FOlmSaipooQdh_vIciKNe21VDHn6AFHBoTZdf2Spq8TRi86bkv0y0FjT2wEuh6WJ6TsT8XBO-hcX_PbEV5R5-1KerFUUL1yJ924zIfpoUheekhCt5B9vfs2eUaDJaOOKxGL"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768190509.557705,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GAPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1:Rx7ze36TKRXzzT5NEQG0R7zJ5ae6ECFS6nVR3gegrCTelqF7-kJ9Y0lMfQCSA8gDPP_Lu8Ev1gMPCN4sSjOjADrbBcNUiQ:quVuVQI03VUpb3vc"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768190509.633757,
        "hostOnly": true,
        "httpOnly": true,
        "name": "LSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQiiPUJLG-oiXSj7i1pMfi_YF2HRD0U9UMWUXnjJZv3QU7U9ZOxFpPmxGWhRJf1SEb3VLg."
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768190509.633847,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-1PLSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQiiPUJLG-oiXSj7i1pMfi_YF2HRD0U9UMWUXnjJZv3QU7U9LlolVuldX8W32qGz2wdJ-Q."
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768190509.633937,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-3PLSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQiiPUJLG-oiXSj7i1pMfi_YF2HRD0U9UMWUXnjJZv3QU7U9BPTqmz9W1ldTL7nAXOvAwA."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1736654509.802988,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjEBPVxjStsSf73eCuNOBbR3FDTlWubhg7Wvi1ujHymQDy11nftJ1B49vPFPRp_tJ7ZFEAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768190509.803093,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQiiPdLu0pyCtWook8rSb0OfvXSUhaHDOz_brEHZG_gyWqe-HBLjuqPc4TgD3cbIqD34PA."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768190509.803323,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "MtqtvSoZowUKlMU8/AeZ9f2wc9nvl6Zwot"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768190510.066919,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQiiPdLu0pyCtWook8rSb0OfvXSUhaHDOz_brEHZG_gyWqe-HBLjuqPc4TgD3cbIqD34PA."
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768190510.067209,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "MtqtvSoZowUKlMU8/AeZ9f2wc9nvl6Zwot"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1720929710.067264,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "511=Oo3gW3ieiGGwAUliAdrsNODc5oOnEv7BNParwyWwoYr3ZWEoCVzMWKuc4YjDpCDKwrdRKxN0dHV77QgkjIXlTaiv3LFtupCyDdTQFtYLaD-IBJf0q8v7Ndj4GHQ1khQUnKJEPqGjN6FxapcXR8iBpT7cLiUeha1yAOEqkc9_KDI"
    },
    {
        "domain": "www.google.com",
        "expirationDate": 1705119110,
        "hostOnly": true,
        "httpOnly": false,
        "name": "DV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "Q0rU6hMyelcgMMNiN6YW-gbEeLoP0BjeCHNonvMx_AAAAAA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720929710.894706,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "511=bjDg6aynOnlQ8POHkq9jXWE6GIYOAnNjh-hCVjjX8dGjZTIwsnm5oKPH9zNImX-JMDzMofEByu5YibDJyAqoY-NpCibzi_epa6RjkyRSfBHlR1crXztnm_IsIAE12amrCnGZEImSJip6ZM39e79i_-kQoELrToXRHQne3MbVxIVGfsDKy2zhygsXSZDW4R7YpW0uhW7OscyV6PdkAtMruRNemG0H20-4Eth55Cz0tPCfYN3J5CWUHCo2qfAjDb65ANV9EmGe4laydi9eQNfOcRdJifcuv1dOiWbhpzsVbAMJALX20JY6z9t179o"
    },
    {
        "domain": ".youtube.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "YSC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "xQMldvJoHV8"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768190511.238097,
        "hostOnly": false,
        "httpOnly": true,
        "name": "LOGIN_INFO",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFmmF2swRAIgRtfukzdKC5KfOlrVkfCIjcEVSMq_p_h2f4eRCLNuvRoCIDf5ZPoCqZWPN_NxoGFAzDs_hIEuadh9qVfe31SwuvyW:QUQ3MjNmemdwYU9FZWFaRjRWbE1uWTlVZFh5d3Vpdnk0S2pqRTR4YklkVjJ1RlQyTjR5WVQ1VFI0YmJaLUJfdTlUM2Y0QkZkOEhGZ2pLZ3Bqc1R1aDNqNnZuMHRsaDBBMm9aOWVObFVwU2UtSWtxTmVBZkswUHFVekNxb0hFVjcwOVRiZWlZY1F3QkRBM0VJVG0zN2xiY3ZXYmtZSllCUGtn"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1736654511.423551,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQFYix6CkfMnQ0CuOYDxXq3MMecx7SwuDBBFgREV0XwrBsQxrHbjn1OQQatbMth5kxGI"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736654511.866346,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQHq5F5f5hVTGGPtdL_uiJARzMLM5zmFOYn_fauMAva941D5K-Js9IC-j1ljBLN0N1-o"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736654511.866492,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQFAb0Z394hSSJ2M6ZiV0p-cMGXdrqqdwjvhAnGiI6gatKC_6Mi4n788n8mYrSkRNrtO"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736654511.866601,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQEVEI-UyDcFGlXwUDBbKFfLLccfI3O2QxHIggUKkIdssld55xaT0qpWIafw9Rp26KkhhA"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1739678553.227789,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "VguiZfws7PV0SgBTuFg-BnlX"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1705723375,
        "hostOnly": false,
        "httpOnly": false,
        "name": "dpr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1.25"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1736654572.972711,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "100042388955401"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1736654572.972795,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "9%3AuGlXPCQiygCsWA%3A2%3A1705118570%3A-1%3A6256"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1712894573.307386,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0xNzvOlbLMbOlAYUL.AWUdlCVoHZOgd4ZKfyqxckOo6V8.BloAn3.ej.AAA.0.0.Blogts.AWUFU_9_cl8"
    },
    {
        "domain": ".facebook.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "presence",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1705118579251%2C%22v%22%3A1%7D"
    }
]
 const cookie2 = [
    {
        "domain": ".google.com",
        "expirationDate": 1706198209.584558,
        "hostOnly": false,
        "httpOnly": true,
        "name": "TAID",
        "path": "/ads/measurement",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXK33AtDEZv6gFJyBtbGch7mUL_2sjPI3331BnZ8FHtXPunTno_3Er88feoXHwB-z4lwcYL7Ve0xz7_RWiGJIuyfOKy8ebFFrDiXt139MCby3wDx-4g7FysagiRpdhXgSXyGbQ"
    },
    {
        "domain": "mail-ads.google.com",
        "expirationDate": 1705768347.560173,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/mail/u/0",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gmail=CsQBAAlriVc01xyZ2clzpCQGss9gZDhS7yOxs2XUf2Al34pj49P6uJMJsgJ2IKbSxrRWXNLSVxHB67oz-aoghp3-H_j862qcW22by7GC1K1zyzBGkcU4v-Cc5_UazwGSDvprcgrAiooQubxD01j6vai6xD4M4KkObY7ak7iF0vrWvi7MsJfBZ2qmlPsyQyxZRMkeXjGwhqKq5e2qas3fxwK_MuysdvfeCAmjXE_wFBx6uOUf3-fO0tSVTlWBGOo1eh5GDyBlURDlqfusBhr9AQAJa4lXCu4BiI5WBsHB8hBN99ynbU41tm_32qvV3xuxdk5bJPKVpQ8vhjyRhyVhg_Cw_UDzVVbvZaj1n8HAr06R-bjLJTBQd2Lv-jEyNT0_TfhtNloyhl5jTYQ8QM5cZk72S_d3duIhez4jh2rpgogzYmGJMSRhkmBufEdgfAvluv1MYu44cgKeN3kJby9ymoyU4Wb8Zc2azjF5-muZl2BGR5W9hLI14biDg20weD-phfkGlxt6txh1RdBspwavOE6kyvaMzPUpebLwWdSuLAMuGZF0WEkSisoZJqUEug4HeGWBs3tu-Tky9LiXA1jkVCQ53Z0HsiwvAtAHFKgwAQ"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1705768353.672235,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/mail/u/0",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gmail=CsQBAAlriVc01xyZ2clzpCQGss9gZDhS7yOxs2XUf2Al34pj49P6uJMJsgJ2IKbSxrRWXNLSVxHB67oz-aoghp3-H_j862qcW22by7GC1K1zyzBGkcU4v-Cc5_UazwGSDvprcgrAiooQubxD01j6vai6xD4M4KkObY7ak7iF0vrWvi7MsJfBZ2qmlPsyQyxZRMkeXjGwhqKq5e2qas3fxwK_MuysdvfeCAmjXE_wFBx6uOUf3-fO0tSVTlWBGOo1eh5GDyBlURDUjPusBhr9AQAJa4lXCu4BiI5WBsHB8hBN99ynbU41tm_32qvV3xuxdk5bJPKVpQ8vhjyRhyVhg_Cw_UDzVVbvZaj1n8HAr06R-bjLJTBQd2Lv-jEyNT0_TfhtNloyhl5jTYQ8QM5cZk72S_d3duIhez4jh2rpgogzYmGJMSRhkmBufEdgfAvluv1MYu44cgKeN3kJby9ymoyU4Wb8Zc2azjF5-muZl2BGR5W9hLI14biDg20weD-phfkGlxt6txh1RdBspwavOE6kyvaMzPUpebLwWdSuLAMuGZF0WEkSisoZJqUEug4HeGWBs3tu-Tky9LiXA1jkVCQ53Z0HsiwvAtAHFKgwAQ:gmail_ps=CrEBAAlriVeqZ2DL4aSq5KpcV6hDSmMfCh0fhz6AscdczzMyJk_RqUU3tXnITt3wc6foLlCKFbU6Y9R7jF9rjnBsyO2IhSvNqQ_SfVNzUn_uOWGpgpCGzSjkBJejMUsXcFl6bBHerOvvTIj_Ict6q-3WGk5gTCqZvzeHSXehpa0vYDVe5nkP9afcPzln-clqY3ZXeflFOuZ5qs1PBL6G_IJWYKnwbwID-9rrjCgpW6oBIRNLEKOp-6wGGuoBAAlriVdGHLC-ZR8yILcBkOLMxFp48l1719HqBOXNVX1t5T2sfg67ADJfhibSUnkelP1eev4DqrPvu8e_FPmqODojC_yOOnnBrem26ndbvn68PLyyt7IYVVs3B9eDeWu1t_6gH7gQXIV4lfOmAen4KExQO62kyKkyEp69OX6MznSQzqiImmt4f_8CPfNu1V7xmUChagawVdYE19owkegaX-LdeE60p7YHb7OgR7P2m_NKqXbgnuDp0huNUUFmAbqCloM74-PqNTnmHNHG8SMZqQHnwni332wXWErcyr_dHnJ6oMyhNscBjEUAMAE"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1705768864.880335,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/sync/u/0",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "bigtop-sync=CsEBAAlriVcVgUu_IEj-uGabxCOnhMS-eRml7f_VaHaey6Rtp-_8le9ho_hn1HW5q-c_kI7reqleN2uU-J_Wd84S1XCg8_yQ9eJNY70l_nqyLLLeTyHoxSKXPvinfRSrtOTIT_5OTXZqpotCoiDEOgU5fJIHIeJ-j07e-L2rUGCmlT23fF65VfcXWh8pyh0bDkQVo8DszqnJTnlJrLPZF9r-_7MVxoH_SijA4FQCQEDfTRPu1GRD0dqW0dCS8g5yBX-7LBC6rfusBhr6AQAJa4lXPDHsLfNXYXfQuERPs5nmD9F673o6vCO2G02GRt-BiouTRy27MOMCWxthiKO0pXJHp64JIRg6f8H59Wvlb1HhEHvpxXgqLNAVYFKsyYGwGqH815VfTPGGqFAnNYsXWLKXxFsJt3vyeN8gJvmKUVTJYWGNoPY2JAgGmW6QSQ0r0wuaUegjVaoeYeHDFTNhQCvUJcfgRM3grR6dcEflZG2LvGMsqLnQLYzIIFGI6kqoCsXe9IPKVXJiDywRAADiENE6yTRjfOFOCXeX-r3ABzbf1R6I9bXgAA6h28DJiuISkxkZ3oBZHPhPpwVzpPi5IYPGZGQz7AswAQ"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720713438.005151,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SNID",
        "path": "/verify",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ACX8J6NOLWXQGbY0oADpUuSZ4NxpaEGW6brshHgMK-J0037wCPK9AU-hST2bPyHSdyRWG7vBSuzCPRjNt99W9AknwwP6a1Ri3ow"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1705764757.610821,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/mail",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gmail=CsQBAAlriVc01xyZ2clzpCQGss9gZDhS7yOxs2XUf2Al34pj49P6uJMJsgJ2IKbSxrRWXNLSVxHB67oz-aoghp3-H_j862qcW22by7GC1K1zyzBGkcU4v-Cc5_UazwGSDvprcgrAiooQubxD01j6vai6xD4M4KkObY7ak7iF0vrWvi7MsJfBZ2qmlPsyQyxZRMkeXjGwhqKq5e2qas3fxwK_MuysdvfeCAmjXE_wFBx6uOUf3-fO0tSVTlWBGOo1eh5GDyBlURD_jPusBhr9AQAJa4lXCu4BiI5WBsHB8hBN99ynbU41tm_32qvV3xuxdk5bJPKVpQ8vhjyRhyVhg_Cw_UDzVVbvZaj1n8HAr06R-bjLJTBQd2Lv-jEyNT0_TfhtNloyhl5jTYQ8QM5cZk72S_d3duIhez4jh2rpgogzYmGJMSRhkmBufEdgfAvluv1MYu44cgKeN3kJby9ymoyU4Wb8Zc2azjF5-muZl2BGR5W9hLI14biDg20weD-phfkGlxt6txh1RdBspwavOE6kyvaMzPUpebLwWdSuLAMuGZF0WEkSisoZJqUEug4HeGWBs3tu-Tky9LiXA1jkVCQ53Z0HsiwvAtAHFKgwAQ:gmail_ps=CrEBAAlriVeqZ2DL4aSq5KpcV6hDSmMfCh0fhz6AscdczzMyJk_RqUU3tXnITt3wc6foLlCKFbU6Y9R7jF9rjnBsyO2IhSvNqQ_SfVNzUn_uOWGpgpCGzSjkBJejMUsXcFl6bBHerOvvTIj_Ict6q-3WGk5gTCqZvzeHSXehpa0vYDVe5nkP9afcPzln-clqY3ZXeflFOuZ5qs1PBL6G_IJWYKnwbwID-9rrjCgpW6oBIRNLEIKN-6wGGuoBAAlriVdGHLC-ZR8yILcBkOLMxFp48l1719HqBOXNVX1t5T2sfg67ADJfhibSUnkelP1eev4DqrPvu8e_FPmqODojC_yOOnnBrem26ndbvn68PLyyt7IYVVs3B9eDeWu1t_6gH7gQXIV4lfOmAen4KExQO62kyKkyEp69OX6MznSQzqiImmt4f_8CPfNu1V7xmUChagawVdYE19owkegaX-LdeE60p7YHb7OgR7P2m_NKqXbgnuDp0huNUUFmAbqCloM74-PqNTnmHNHG8SMZqQHnwni332wXWErcyr_dHnJ6oMyhNscBjEUAMAE"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1738656000.584728,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AID",
        "path": "/ads",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXItIz97cRHBERaN3NkAB4wnaps7jrQIPVt6Qu4rAdd1DJrGpYiibfY"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1707492637,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7376611_28_28__28_"
    },
    {
        "domain": "myaccount.google.com",
        "expirationDate": 1707492673,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7376611_28_28__28_"
    },
    {
        "domain": "www.google.com",
        "expirationDate": 1707492675,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7376611_28_28__28_"
    },
    {
        "domain": "ogs.google.com",
        "expirationDate": 1707492678,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7376611_28_28__28_"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1707492734.377462,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GMN",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1707492734.377532,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GMS",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1707492734.377578,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GML",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720452737.096689,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQIlJoB"
    },
    {
        "domain": "contacts.google.com",
        "expirationDate": 1707492741,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7376612_28_28__28_"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1739678454.25718,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ermeZX-DrQOkvmetdL2c5c7K"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1705723259,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1536x754"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1720454238.911989,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_INFO1_LIVE",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "5WQZkDM3vy4"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1767974241,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.3.583799675.1704902241"
    },
    {
        "domain": ".chromewebstore.google.com",
        "expirationDate": 1767974262,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.864033894.1704902263"
    },
    {
        "domain": "chromewebstore.google.com",
        "expirationDate": 1707494262,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7376638_28_28__28_"
    },
    {
        "domain": ".chromewebstore.google.com",
        "expirationDate": 1767977788,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_KHZNC1Q6K0",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1704905788.2.0.1704905788.0.0.0"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1767977788,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_Q3KJSFNQDY",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1704905788.2.0.1704905788.0.0.0"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.239706,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fQi795W1rdMik5PgcpAgEAlCj78cDlplc8RgV3dM9O5nXDlvOVLESXAT5jPP1gQimXoNPA."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.239851,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQi795W1rdMik5PgcpAgEAlCj78cDlplc8RgV3dM9O5nXDlv6TFtCDRyWB4OcLAYC0iYiA."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.239969,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQi795W1rdMik5PgcpAgEAlCj78cDlplc8RgV3dM9O5nXDlv4NgmtXchIYcKoTtUiuMZcQ."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.240382,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ADl2L-V2KMYPVRdPY"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.240484,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AH9A5HHrsJcPWSqmz"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.240565,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fHnU3Zz15v2431nY/AUOWbCGqWUJ7wp3Lk"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.240649,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sddlt6FLS_khOl9A/APRobfHKG1SQ9d-Tf"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.240747,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sddlt6FLS_khOl9A/APRobfHKG1SQ9d-Tf"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768060597.240846,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sddlt6FLS_khOl9A/APRobfHKG1SQ9d-Tf"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768060597.240929,
        "hostOnly": true,
        "httpOnly": true,
        "name": "ACCOUNT_CHOOSER",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFx_qI6TVTlLdNA-I7MyxRlfj-ouAppwsxXigu80QgaB3Dv8K3QfE5T-QdBEiZ7vkKgVNuhUkPn1NcZqgyxQ8agc6iLvv3CXxT8a1Ut1_NUpQKCwOoDufs2s4Pr3EFDAbk5BzjLeE731"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768060597.241029,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GAPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1:Ei8cQCc-72Yx3Oqf28sYpufDAngzH7zJXXsCsbGiQe6V51F8vTKOYHBPr8eoFU3Ag9jVO2Ra_bTsE4gyjsIKx4dhfmJ5Yw:wFhU8p_3uwSfx7x-"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768060597.314023,
        "hostOnly": true,
        "httpOnly": true,
        "name": "LSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQi79xIqz0YtI7aN9Cov0yiHjMB4rGLQhyl97ZuxkgOs1H9m4KDOOIu-ALcbTqP_b6a15A."
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768060597.314172,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-1PLSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQi79xIqz0YtI7aN9Cov0yiHjMB4rGLQhyl97ZuxkgOs1H9mWNbovUqnsj2u6AX5RpB60Q."
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768060597.314285,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-3PLSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQi79xIqz0YtI7aN9Cov0yiHjMB4rGLQhyl97ZuxkgOs1H9mQPhXBMfqmsAVdvYwVhRAJw."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1736524597.443684,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjEBPVxjStd2q1RTlg-hgC2AcWZ3J8kgURekKH_UVQ3UCHT8rd6TQM-tVnXF_hVw3RR4EAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768060597.443836,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQi795W1rdMik5PgcpAgEAlCj78cDlplc8RgV3dM9O5nXDlv4NgmtXchIYcKoTtUiuMZcQ."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768060597.444069,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sddlt6FLS_khOl9A/APRobfHKG1SQ9d-Tf"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768060597.60856,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQi795W1rdMik5PgcpAgEAlCj78cDlplc8RgV3dM9O5nXDlv4NgmtXchIYcKoTtUiuMZcQ."
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768060597.608797,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sddlt6FLS_khOl9A/APRobfHKG1SQ9d-Tf"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1720799797.608852,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "511=FcAsD3HBsFsdRIezpzR2XPJxGaIrEvUIUEhoUnCb2E1ckpR10-LTCuabonHGSozwuPfWyv3G3Fd535xikQvEVS7hDoCmaXTRWd2Zpx6woVjIkgoONuO69WeZD6RMNaM-DoMOZ1wFV_l8ss3ehYJkoIeuAeKYue6qKtAPxZLObaw"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1707580609.696261,
        "hostOnly": false,
        "httpOnly": false,
        "name": "1P_JAR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "2024-01-11-15"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720452755.745898,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Ae3NU9PsaKbOUAfdqhK3cZOafXvYWZGWAyqkEBw83MGVhDyVEYKYK4XobA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720799807.00502,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "511=HruMRp_EhzXcZXMv9N2dajKE1WyjVhqf_U-T8CffE60AwtYtbNQN_mVxlPbEnYq3dtvTTBC6W9nBtip9_2tzH4LXeS4e0CS2YS9oWZbJYm9lfAvfWXzS4AnolHJRJz8AHdUiVBiCq7cJ6rDUPVtu6B2MRS04RenuypEL_Pyon6A__Vz4pXcMOxWYu9DtMX6TaJRK-9MTffuzeX9Kb-nNJ7RsxfSnYWhKx6AXtUrN28Op9ToFjSdDh-uoYo87lyt_gDs735vtmdwCXElHiUVW4xryd1MBabhNEVwGoOqg3Q5J6bYy7j8-8gPuY6Et"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736524608.774468,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjEBPVxjSsQghVVDvtG2VBmsvNprgxcBEOZM3sbl2S5Oegb7H3o_cBOt8wnjpF_5ML27EAA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736524608.774551,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjEBPVxjSsQghVVDvtG2VBmsvNprgxcBEOZM3sbl2S5Oegb7H3o_cBOt8wnjpF_5ML27EAA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736654340.334386,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQFHGLVCd2CBF5YT6RYGOb6prd5Dz56RQqTWIImIq7CznGcuvoeza4zPguWeAK4L3SywIA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736654340.334481,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQFqhllHngr1_0HO57D_etKY9-exkvWA41XC1-sqEyUDuQtnQIk0Bnf8geBrcFOmcqJ4"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736654340.33456,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQHEwi_69JFPHjrlvZTle0yYNVCgw7nrDb8ixMbl9G6iThkRNcSk-SUOQ_hvZVryeXw9-w"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1739678364.840681,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "mAqiZX_6SBOVy53873iRhR6U"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1705723259,
        "hostOnly": false,
        "httpOnly": false,
        "name": "dpr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1.25"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1736654454.257472,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "100019313437601"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1736654454.257537,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "34%3AeXNYSdA0t24Hjw%3A2%3A1705118450%3A-1%3A6270"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1712894455.031117,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1WEGcqMNlwYXgMSL1.AWWeI5SVQ1Lh9Z7bQnT7Jfz4kG8.BloA_N.UI.AAA.0.0.Blogr1.AWVUXmT9tzo"
    },
    {
        "domain": ".facebook.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "presence",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1705118461411%2C%22v%22%3A1%7D"
    }
]
const cookie3 =[
    {
        "domain": ".google.com",
        "expirationDate": 1706292571.260584,
        "hostOnly": false,
        "httpOnly": true,
        "name": "TAID",
        "path": "/ads/measurement",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXKHRsOOchtKeqCU-PqTqVxTwgIBFAVLGMg5dYO41i9-0EWLxA-B7bfr6FXeW-vWwE7quJ-Tdqq4AyKSvNy71tCS3W5YCiYzEC81WHzJVkWgHJQpMhjFMjd7iDHT8-5B1d4ZKZM"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720799630.087106,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SNID",
        "path": "/verify",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ACX8J6OUzljalHZuJY-ouMkEimFXTk2cwC2teVhWe-dOCWwq1wHF4Pk4M-RjIV8J9sqwzsQoMPJMwZ42r0j4cK1AJB3_ImEnXYU"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1751698800.260679,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AID",
        "path": "/ads",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AJHaeXK3oF_bnQrNBEQePwVFRnl2r_clrI2S8GSQR-Q"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1707579895,
        "hostOnly": true,
        "httpOnly": false,
        "name": "OTZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7378065_28_28__28_"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.961389,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcKoVtqZPd3TWfuyKK16NKEA."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.961453,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcS0RsH0oFlE-YNjTKp1LgsA."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.961496,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorc7ohMG6DgWgxRgaiHr07jVw."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.961855,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AERSRtI7iVx0jZnip"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.961902,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AmOB1wDmjL5nl9KJy"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.961946,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0YjPwaMIOVPClvmJ/AGW8bdTzp-uX-yF7J"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.961981,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.962021,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768059943.962063,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059943.962102,
        "hostOnly": true,
        "httpOnly": true,
        "name": "ACCOUNT_CHOOSER",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFx_qI7oKxH0PbTTKfWggb8VHO8lL3Qkwi29v95Zm8pCajlTItx5MVJQ8ED1vQIaHjYDqoN4czE_n1ud5zwLMPVn5ocD4vRsLzSplCJbHyyR1Tu2sQd9K7a8oD26CFJweSswMz62kiez"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059944.063861,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GAPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1:2mDb7yYPhH31fUTaCqG8tnPrbDNAp50lRSazwBETscC9ixm_PlU88LZ_ABPHmCrhqQxMYmm39syH5jJ9buH7TwQwiyoIjQ:qPIpfZm8ODBnVTOq"
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059944.063957,
        "hostOnly": true,
        "httpOnly": true,
        "name": "LSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQhYhZJCX-H_Ycsx1tlbKjEBqrFUqIwvl061oPLmlWPy7QNQGDXOF8lYzjpr1-DyR95X5A."
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059944.064016,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-1PLSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQhYhZJCX-H_Ycsx1tlbKjEBqrFUqIwvl061oPLmlWPy7QNQvZbzKAmBEkTboXsCFZBG9w."
    },
    {
        "domain": "accounts.google.com",
        "expirationDate": 1768059944.064099,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-3PLSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "s.VN|s.youtube:fQhYhZJCX-H_Ycsx1tlbKjEBqrFUqIwvl061oPLmlWPy7QNQ8DwGyZud3I9Ke7T2xsEbEA."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118728,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcKoVtqZPd3TWfuyKK16NKEA."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1736523944.118775,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjIBPVxjSr5OJG9WetvCn-L7bbEYsMwua7zQjXaT1rJOi8EXd00kXDeWVspXVMVZoW4z3hAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1736523944.118824,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjIBPVxjSr5OJG9WetvCn-L7bbEYsMwua7zQjXaT1rJOi8EXd00kXDeWVspXVMVZoW4z3hAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118854,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcS0RsH0oFlE-YNjTKp1LgsA."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118881,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorc7ohMG6DgWgxRgaiHr07jVw."
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.11891,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AZMUyGbUwYcuod6Ds"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118936,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFMekpXWCEGqB_8zQ"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118959,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0YjPwaMIOVPClvmJ/AGW8bdTzp-uX-yF7J"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.118983,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.119017,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1768059944.119042,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.259842,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcKoVtqZPd3TWfuyKK16NKEA."
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.259911,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorcS0RsH0oFlE-YNjTKp1LgsA."
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.259963,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fQhYhQG157aB5Wz367PP7u5IVYcCseawI0dxFLvZqjnKyorc7ohMG6DgWgxRgaiHr07jVw."
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260036,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AZMUyGbUwYcuod6Ds"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.26008,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFMekpXWCEGqB_8zQ"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260114,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0YjPwaMIOVPClvmJ/AGW8bdTzp-uX-yF7J"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260137,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260162,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1768059944.260204,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "KIbK1tKCFNyLEFbk/AVSHIhxtlMUJST7zx"
    },
    {
        "domain": ".google.com.vn",
        "expirationDate": 1720799144.260234,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "511=YJSFmYnerRyJbfyts6OEkw0GV4qsiAKquu9ggpsO1Ef8Zsa62qtTINhGdLYnQhQlBUbIRAba3y6JA6ThSD5jiskADH_WoWFsawpjv-UU_O9SOagM4CBoyIyjyyzqlD6MxTuy6KQWEDgA2Ly1j8Y0NGZ-oXaWveKbseCj0swEiX8"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720539967.321085,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQIlZoB"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1739643090.265792,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Qg2gZSwcnQ_Y-ULi9_QAne0r"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1739548174.238777,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Qg2gZUsKPeCoWhdu-OwCnGgl"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1705687892,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1536x754"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1768060433,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.3.1823323768.1704988433"
    },
    {
        "domain": ".chrome.google.com",
        "expirationDate": 1768060446,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_Q3KJSFNQDY",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1704988433.1.1.1704988446.0.0.0"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1707674970.06664,
        "hostOnly": false,
        "httpOnly": false,
        "name": "1P_JAR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "2024-01-12-18"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720539967.897379,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Ae3NU9M93Qh0x_5Bs19ucnOSn3uVWt-xOK9VYeKPMS6Jwi2b4TkMGBRDnXY"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1720894168.087,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "511=Lc-f4kk5Kn6j5ZcotumCZNvcW06iS4hMdoocF1fgNcDwf9mqE1XuQWB8vsP8LgLEmDjdjZk5TjngQ8Hx_kCOHw6eWSByKWG227FuO9o8Q9ZTsDPMpQd7bWqoI_FfN5G-jS0BXVPjsR9VHHisU1RwehNZ4uyxLo29L1PVLWCnWYokU0ck6U4y3d3S1dv4BOPkodQ8BCsvZ83yllmvy-LVgNn4Ot-CcVayfqwpGjZQ15DUjMS5x2ru2YdLYL85xhCVq-_Nf4w_xQb1CGcZbMj_glgXGmDTC15ekiGrbaxyzqdwWD5coxETJm7N"
    },
    {
        "domain": "www.google.com",
        "expirationDate": 1705083569,
        "hostOnly": true,
        "httpOnly": false,
        "name": "DV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "Y6ek9wzjBMdSECBuCtWvdH3HRdXtz1gtWN6v3q37uwAAAICGSTB--aTygAAAAKTBR8P1m8U1JAAAAPob2FmvhbQoEwAAAA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736618970.353154,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQF4gJmu5xp832KyO0ZC7kBPHw7PtIX9CQSxefao-SyNpZ04PpS4iJ8npAHxOt9OR2LIhw"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736618970.353255,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQHZQA3CORUkpv5andOYTyVWFMcROvslsjBE9HIzSIC9ut2nzNsP98aMCqO-0H8IEEn2"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1736618970.35333,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ABTWhQFcWqUvL-TuqtA41yPVAaA4K9rwdBp0DDCjNQ4UjCfDtfc914pca72E2E61l6mmhmnBDw"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1705687892,
        "hostOnly": false,
        "httpOnly": false,
        "name": "dpr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1.25"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1736619090.265939,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "100042782445854"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1736619090.266027,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1%3A_cb2lE5MaOPzRw%3A2%3A1705083089%3A-1%3A6156"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1712859090.26609,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0UEFw6T1i2PRKvDLT.AWUMsXydLcbgNm1i6R_eA9TdlNs.BloA1C.3-.AAA.0.0.BloYDO.AWV8UORygyM"
    },
    {
        "domain": ".facebook.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "presence",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1705083094601%2C%22v%22%3A1%7D"
    }
]
const scrollAll =async ()=>{
    Promise.all([ScrollToGetPost(cookie1),ScrollToGetPost(cookie2),ScrollToGetPost(cookie3)]);
}
(async()=>await scrollAll())();